// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTTicTacToe.CQRS.Database;

namespace RTTicTacToe.CQRS.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181206082512_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("RTTicTacToe.CQRS.Database.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("LastChangeDate");

                    b.Property<string>("Name");

                    b.Property<Guid?>("Player1Id");

                    b.Property<Guid?>("Player2Id");

                    b.Property<int>("Version");

                    b.Property<Guid?>("WinnerId");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RTTicTacToe.CQRS.Database.Models.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid?>("GameId");

                    b.Property<DateTime>("LastChangeDate");

                    b.Property<Guid>("PlayerId");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("RTTicTacToe.CQRS.Database.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("LastChangeDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RTTicTacToe.CQRS.Database.Models.Game", b =>
                {
                    b.HasOne("RTTicTacToe.CQRS.Database.Models.Player", "Player1")
                        .WithMany("GamesAsPlayer1")
                        .HasForeignKey("Player1Id");

                    b.HasOne("RTTicTacToe.CQRS.Database.Models.Player", "Player2")
                        .WithMany("GamesAsPlayer2")
                        .HasForeignKey("Player2Id");

                    b.HasOne("RTTicTacToe.CQRS.Database.Models.Player", "Winner")
                        .WithMany("GamesWon")
                        .HasForeignKey("WinnerId");
                });

            modelBuilder.Entity("RTTicTacToe.CQRS.Database.Models.Movement", b =>
                {
                    b.HasOne("RTTicTacToe.CQRS.Database.Models.Game", "Game")
                        .WithMany("Movements")
                        .HasForeignKey("GameId");
                });
#pragma warning restore 612, 618
        }
    }
}
